Attribute VB_Name = "TargetsEditor"
Option Explicit

' ============================================================================
' targets-editor  -  Export "Targets" sheet to network-check targets.lst
'
' Sheet layout (data starts at row 2):
'   A: Section   B: Host   C: Port   D: Expected   E: Description
'
' Output contract:
'   - UTF-8 without BOM, LF line endings
'   - 4-field format: <host>, <port>, <expected>, <description>
'   - Section change emits a blank line + "# ---- <Section> ----" comment
' ============================================================================

Private Const SHEET_NAME As String = "Targets"
Private Const FIRST_DATA_ROW As Long = 2
Private Const COL_SECTION As Long = 1
Private Const COL_HOST As Long = 2
Private Const COL_PORT As Long = 3
Private Const COL_EXPECTED As Long = 4
Private Const COL_DESC As Long = 5

Public Sub ExportTargets()
    Dim ws As Worksheet
    On Error Resume Next
    Set ws = ThisWorkbook.Worksheets(SHEET_NAME)
    On Error GoTo 0
    If ws Is Nothing Then
        MsgBox "Sheet '" & SHEET_NAME & "' not found.", vbCritical, "targets-editor"
        Exit Sub
    End If

    Dim lastRow As Long
    lastRow = ws.Cells(ws.Rows.Count, COL_HOST).End(xlUp).Row
    If lastRow < FIRST_DATA_ROW Then
        MsgBox "No data rows (row 2 and below are empty).", vbExclamation, "targets-editor"
        Exit Sub
    End If

    Dim errs As String
    errs = ValidateRows(ws, lastRow)
    If Len(errs) > 0 Then
        MsgBox "Validation failed. Fix the highlighted cells:" & vbCrLf & errs, _
               vbCritical, "targets-editor"
        Exit Sub
    End If

    Dim outPath As Variant
    outPath = Application.GetSaveAsFilename( _
        InitialFileName:="targets.lst", _
        FileFilter:="Target list (*.lst),*.lst,All files (*.*),*.*")
    If VarType(outPath) = vbBoolean Then Exit Sub   ' user cancelled

    WriteUtf8NoBomLf CStr(outPath), BuildContent(ws, lastRow)
    MsgBox "Exported: " & outPath, vbInformation, "targets-editor"
End Sub

' Returns "" when all rows are valid; otherwise a CRLF-joined error summary.
' Invalid cells get a light red interior; valid cells are reset.
Private Function ValidateRows(ByVal ws As Worksheet, ByVal lastRow As Long) As String
    Dim r As Long, errs As String
    Dim host As String, port As String, expected As String

    For r = FIRST_DATA_ROW To lastRow
        ws.Range(ws.Cells(r, COL_HOST), ws.Cells(r, COL_EXPECTED)).Interior.ColorIndex = xlNone

        host = Trim$(CStr(ws.Cells(r, COL_HOST).Value))
        port = Trim$(CStr(ws.Cells(r, COL_PORT).Value))
        expected = LCase$(Trim$(CStr(ws.Cells(r, COL_EXPECTED).Value)))

        If Len(host) = 0 Then
            ws.Cells(r, COL_HOST).Interior.Color = RGB(255, 200, 200)
            errs = errs & "Row " & r & ": Host is empty" & vbCrLf
        ElseIf InStr(host, ",") > 0 Then
            ws.Cells(r, COL_HOST).Interior.Color = RGB(255, 200, 200)
            errs = errs & "Row " & r & ": Host must not contain ','" & vbCrLf
        End If

        If Not IsValidPort(port) Then
            ws.Cells(r, COL_PORT).Interior.Color = RGB(255, 200, 200)
            errs = errs & "Row " & r & ": Port must be 1-65535 or '-'" & vbCrLf
        End If

        If expected <> "ok" And expected <> "ng" And expected <> "-" And Len(expected) > 0 Then
            ws.Cells(r, COL_EXPECTED).Interior.Color = RGB(255, 200, 200)
            errs = errs & "Row " & r & ": Expected must be ok / ng / -" & vbCrLf
        End If
    Next r

    ValidateRows = errs
End Function

Private Function IsValidPort(ByVal port As String) As Boolean
    If port = "-" Or Len(port) = 0 Then
        IsValidPort = True
    ElseIf IsNumeric(port) Then
        IsValidPort = (CDbl(port) >= 1 And CDbl(port) <= 65535 And CDbl(port) = Int(CDbl(port)))
    Else
        IsValidPort = False
    End If
End Function

' Builds the full file content. Lines are joined with LF only.
Private Function BuildContent(ByVal ws As Worksheet, ByVal lastRow As Long) As String
    Dim sb As String, r As Long
    Dim section As String, prevSection As String
    Dim host As String, port As String, expected As String, desc As String

    sb = "# Network connectivity check target list" & vbLf & _
         "# Generated by targets-editor.xlsm" & vbLf & _
         "#" & vbLf & _
         "# 4-field format: <host>, <port>, <expected>, <description>" & vbLf & _
         "#   expected: ok (expect reachable) / ng (expect unreachable) / - (no eval)" & vbLf & _
         "#   port:     TCP port number, or '-' for ping-only" & vbLf

    prevSection = Chr$(0)   ' sentinel: never equals a real section
    For r = FIRST_DATA_ROW To lastRow
        host = Trim$(CStr(ws.Cells(r, COL_HOST).Value))
        If Len(host) > 0 Then
            section = Trim$(CStr(ws.Cells(r, COL_SECTION).Value))
            port = Trim$(CStr(ws.Cells(r, COL_PORT).Value))
            expected = LCase$(Trim$(CStr(ws.Cells(r, COL_EXPECTED).Value)))
            desc = Trim$(CStr(ws.Cells(r, COL_DESC).Value))
            If Len(port) = 0 Then port = "-"
            If Len(expected) = 0 Then expected = "-"

            If section <> prevSection Then
                sb = sb & vbLf
                If Len(section) > 0 Then
                    sb = sb & "# ---- " & section & " ----" & vbLf
                End If
                prevSection = section
            End If
            sb = sb & host & ", " & port & ", " & expected & ", " & desc & vbLf
        End If
    Next r

    BuildContent = sb
End Function

' Writes content as UTF-8 WITHOUT BOM. ADODB's utf-8 charset always writes a
' 3-byte BOM, so re-read the text stream as binary from position 3 and save.
Private Sub WriteUtf8NoBomLf(ByVal filePath As String, ByVal content As String)
    Dim textStream As Object, binStream As Object
    Set textStream = CreateObject("ADODB.Stream")
    textStream.Type = 2                 ' adTypeText
    textStream.Charset = "utf-8"
    textStream.Open
    textStream.WriteText content

    textStream.Position = 0
    textStream.Type = 1                 ' adTypeBinary
    textStream.Position = 3             ' skip BOM (EF BB BF)

    Set binStream = CreateObject("ADODB.Stream")
    binStream.Type = 1
    binStream.Open
    textStream.CopyTo binStream
    binStream.SaveToFile filePath, 2    ' adSaveCreateOverWrite
    binStream.Close
    textStream.Close
End Sub
